# @timeout 6000
POST http://127.0.0.1:3000/gemini
Content-Type: application/json

{
  "amountOfQuestions": 50,
  "amountOfOptions": 4,
  "amountOfMultipleAnswerQuestions": 5,
  "ignoreContext": true,
  "content": ""
}

###